name: .NET CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: windows-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore E-commerce.sln

    - name: Build
      run: dotnet build E-commerce.sln --configuration Release --no-restore

    - name: Run Tests with Coverage
      run: dotnet test E-commerce.sln --no-restore --verbosity normal

    - name: Check StyleCop (opsiyonel)
      run: dotnet build E-commerce.sln --configuration Release --no-restore

    - name: Generate HTML Coverage Report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coveragereport -reporttypes:Html
    - name: Annotate StyleCop Warnings
      uses: xt0rted/dotnet-format-problem-matcher@v1

    
